# PowerShell Setup Script for Raspberry Pi Remote Commands
# Run this script to set up SSH keys and PowerShell functions

Write-Host "=== Raspberry Pi Remote Commands Setup ===" -ForegroundColor Cyan
Write-Host ""

# Configuration
$PI_USER = "frc4607"
$PI_HOST = "frc4607-spatial-ai"
$PI_FULL = "$PI_USER@$PI_HOST"

# Step 1: Check if SSH key exists
Write-Host "Step 1: Checking for SSH keys..." -ForegroundColor Yellow
$sshKeyPath = "$env:USERPROFILE\.ssh\id_rsa"

if (-not (Test-Path $sshKeyPath)) {
    Write-Host "No SSH key found. Generating new SSH key..." -ForegroundColor Green
    ssh-keygen -t rsa -b 4096 -f $sshKeyPath -N '""'
    Write-Host "SSH key generated at $sshKeyPath" -ForegroundColor Green
} else {
    Write-Host "SSH key already exists at $sshKeyPath" -ForegroundColor Green
}

# Step 2: Copy SSH key to Pi
Write-Host ""
Write-Host "Step 2: Copying SSH key to Raspberry Pi..." -ForegroundColor Yellow
Write-Host "You will be prompted for the Pi's password." -ForegroundColor Cyan

# Check if ssh-copy-id exists (it doesn't by default on Windows)
$sshCopyIdExists = Get-Command ssh-copy-id -ErrorAction SilentlyContinue

if ($sshCopyIdExists) {
    ssh-copy-id $PI_FULL
} else {
    Write-Host "ssh-copy-id not found. Using alternative method..." -ForegroundColor Yellow
    $pubKey = Get-Content "$sshKeyPath.pub"
    $command = "mkdir -p ~/.ssh && echo '$pubKey' >> ~/.ssh/authorized_keys && chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys"
    ssh $PI_FULL $command
}

Write-Host "SSH key copied successfully!" -ForegroundColor Green

# Step 3: Test SSH connection
Write-Host ""
Write-Host "Step 3: Testing SSH connection (should not prompt for password)..." -ForegroundColor Yellow
ssh $PI_FULL "echo 'Connection successful!'"

if ($LASTEXITCODE -eq 0) {
    Write-Host "SSH authentication working!" -ForegroundColor Green
} else {
    Write-Host "SSH test failed. You may need to manually set up key authentication." -ForegroundColor Red
    exit 1
}

# Step 4: Add functions to PowerShell profile
Write-Host ""
Write-Host "Step 4: Adding remote command functions to PowerShell profile..." -ForegroundColor Yellow

# Create profile if it doesn't exist
if (-not (Test-Path $PROFILE)) {
    Write-Host "Creating PowerShell profile at $PROFILE" -ForegroundColor Green
    New-Item -Path $PROFILE -Type File -Force | Out-Null
}

# Functions to add
$functionsToAdd = @"

# ========================================
# Raspberry Pi Remote Commands (frc4607-spatial-ai)
# Generated by setup script
# ========================================

function servicestatus {
    ssh $PI_FULL "sudo systemctl status frc4607-spatial-ai.service"
}

function servicestart {
    ssh $PI_FULL "sudo systemctl start frc4607-spatial-ai.service"
    Write-Host "Service started. Use 'servicestatus' to check status." -ForegroundColor Green
}

function servicestop {
    ssh $PI_FULL "sudo systemctl stop frc4607-spatial-ai.service"
    Write-Host "Service stopped." -ForegroundColor Yellow
}

function servicerestart {
    ssh $PI_FULL "sudo systemctl restart frc4607-spatial-ai.service"
    Write-Host "Service restarted. Use 'servicestatus' to check status." -ForegroundColor Green
}

function viewlogs {
    ssh $PI_FULL "tail -n 1000 /media/RECORDINGS/frc4607-spatial-ai-error.log"
}

function followlogs {
    ssh $PI_FULL "tail -f /media/RECORDINGS/frc4607-spatial-ai-error.log"
}

function deletelogs {
    ssh $PI_FULL "sudo rm -f /media/RECORDINGS/*.log"
    Write-Host "Logs deleted." -ForegroundColor Yellow
}

function fixrecordings {
    ssh $PI_FULL "sudo chown -R frc4607:frc4607 /media/RECORDINGS && sudo chmod -R 775 /media/RECORDINGS"
    Write-Host "Permissions fixed for /media/RECORDINGS" -ForegroundColor Green
}

function pissh {
    ssh $PI_FULL
}

function setcompmode { 
    $PiUser="frc4607";
    $PiHost="frc4607-spatial-ai";
    $RemotePath="/home/frc4607/pi_setup";
    $RunCommand="cd $RemotePath && ./enable_comp_mode.sh";
    Write-Host "Running remote script: $RunCommand" -ForegroundColor Cyan;
    ssh "$PiUser@$PiHost" "bash -lc '$RunCommand'";
    if ($LASTEXITCODE -eq 0) { Write-Host "Enable comp mode successful!" -ForegroundColor Green } 
    else { Write-Error "Enable comp mode failed with exit code $LASTEXITCODE" }
}

function setdevmode { 
    $PiUser="frc4607";
    $PiHost="frc4607-spatial-ai";
    $RemotePath="/home/frc4607/pi_setup";
    $RunCommand="cd $RemotePath && ./enable_dev_mode.sh";
    Write-Host "Running remote script: $RunCommand" -ForegroundColor Cyan;
    ssh "$PiUser@$PiHost" "bash -lc '$RunCommand'";
    if ($LASTEXITCODE -eq 0) { Write-Host "Enable dev mode successful!" -ForegroundColor Green } 
    else { Write-Error "Enable dev mode failed with exit code $LASTEXITCODE" }
}

function copyrecordings {
    param($LocalFolder = ".\recordings");
    $PiUser="frc4607";
    $PiHost="frc4607-spatial-ai";
    $RemoteFile="/media/RECORDINGS";
    if (-not (Test-Path $LocalFolder)) { New-Item -ItemType Directory -Path $LocalFolder | Out-Null };
    Write-Host "Copying from $PiUser@$PiHost:$RemoteFile ..." -ForegroundColor Cyan;
    scp -r "$PiUser@$PiHost:`"$RemoteFile/*`"" "$LocalFolder";
    if ($LASTEXITCODE -eq 0) { Write-Host "Copy completed!" -ForegroundColor Green } 
    else { Write-Host "Copy failed with exit code $LASTEXITCODE" -ForegroundColor Red }
}

Write-Host "Raspberry Pi remote commands loaded. Available commands:" -ForegroundColor Cyan
Write-Host "  servicestatus, servicestart, servicestop, servicerestart" -ForegroundColor White
Write-Host "  viewlogs, followlogs, deletelogs" -ForegroundColor White
Write-Host "  copyrecordings, fixrecordings, pissh, setcompmode, setdevmode" -ForegroundColor White

"@

# Check if functions already exist
$profileContent = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
if ($profileContent -match "Raspberry Pi Remote Commands") {
    Write-Host "Functions already exist in profile. Skipping..." -ForegroundColor Yellow
} else {
    Add-Content -Path $PROFILE -Value $functionsToAdd
    Write-Host "Functions added to PowerShell profile!" -ForegroundColor Green
}

# Step 5: Reload profile
Write-Host ""
Write-Host "Step 5: Loading functions into current session..." -ForegroundColor Yellow
. $PROFILE

Write-Host ""
Write-Host "=== Setup Complete! ===" -ForegroundColor Green
Write-Host ""
Write-Host "Available commands:" -ForegroundColor Cyan
Write-Host "  servicestatus   - Check service status" -ForegroundColor White
Write-Host "  servicestart    - Start the service" -ForegroundColor White
Write-Host "  servicestop     - Stop the service" -ForegroundColor White
Write-Host "  servicerestart  - Restart the service" -ForegroundColor White
Write-Host "  viewlogs        - View last 1000 log lines" -ForegroundColor White
Write-Host "  followlogs      - Live tail of logs (Ctrl+C to exit)" -ForegroundColor White
Write-Host "  deletelogs      - Delete all logs" -ForegroundColor White
Write-Host "  fixrecordings   - Fix permissions on recordings" -ForegroundColor White
Write-Host "  pissh           - SSH into the Pi" -ForegroundColor White
Write-Host ""
Write-Host "Try running 'servicestatus' to test!" -ForegroundColor Yellow